name: les-nicois

# Définir l'environnement de déploiement (ici, Node.js)
type: nodejs:16  # Version de Node.js à utiliser

# Définir la commande à utiliser pour démarrer le serveur
hooks:
  deploy:
    # Utiliser une commande sous forme de chaîne de caractères
    - "npm install"

web:
  locations:
    "/":
      root: "les-Niçois"
      index: "index.html"
      # Le fichier server.js va être utilisé comme le script principal
      scripts:
        start: "server/server.js"

# Il n'est pas nécessaire de spécifier http et port ici, ces valeurs sont gérées automatiquement par Platform.sh.
