name: app

type: "nodejs:16"

web:
  locations:
    "/":
      root: "assets"
      index: ["index.html"]
      allow: true
  commands:
    start: "node server/server.js"

disk: 1024

mounts:
  "/assets": "assets"
