name: les-nicois

# Définir l'environnement de déploiement (ici, Node.js)
type: nodejs:16  # Version de Node.js à utiliser

# Définir la commande à utiliser pour démarrer le serveur
hooks:
  deploy: "npm install"  # Utilisation d'une chaîne de caractères simple pour npm install

web:
  locations:
    "/":
      root: "les-Niçois"  # Répertoire contenant les fichiers statiques
      index: "index.html"  # Fichier index à servir par défaut
      # Utilisation de 'scripts' au lieu de 'script'
      scripts:
        start: "server/server.js"  # Script principal du serveur
