name: les-nicois

# Définir l'environnement de déploiement (ici, Node.js)
type: "nodejs:16"  # Version de Node.js à utiliser (ici, Node.js 16)

# Définir la commande à utiliser pour démarrer le serveur
hooks:
  deploy:
    # Lancer l'installation des dépendances
    - npm install

web:
  # Définir le port d'écoute du serveur (Platform.sh utilise un port dynamique)
  locations:
    "/":
      root: "les-Niçois"
      index: "index.html"
      script: "server/server.js"

  # Spécification du fichier server.js comme script principal
  script: "server/server.js"

  # Configurer l'url d'écoute, Platform.sh utilisera un port dynamique
  http:
    port: $PLATFORM_APP_PORT
