# Nom de l'application
name: app

# Type d'application avec version de Node.js
type: nodejs:16

# Taille du disque allouée (en Mo)
disk: 1024

# Commandes exécutées pendant le build
hooks:
  build: |
    # Accéder au répertoire 'server' à la racine de votre projet
    cd Les-Niçois/server
    npm install

# Commandes exécutées après le déploiement
web:
  commands:
    start: cd Les-Niçois/server && npm start
  locations:
    "/":
      allow: true
