# Nom de l'application
name: app

# Type d'application avec version de Node.js
type: nodejs:16

# Taille du disque allouée (en Mo)
disk: 1024

# Commandes exécutées après le déploiement
hooks:
  build: |
    # Assurez-vous que nous passons dans le dossier 'Les-Niçois/server' avant d'exécuter npm
    cd Les-Niçois/server
    npm install
    npm run build

# Configuration du service web
web:
  commands:
    start: cd Les-Niçois/server && npm start
  locations:
    "/":
      allow: true
