name: app

type: "nodejs:16"

web:
  locations:
    "/":
      allow: true
      index: ["index.html"]
    "/assets":
      root: "assets"
      allow: true

  commands:
    start: "node server.js"

disk: 1024

mounts:
  "/assets": "assets"
