name: les-nicois

# Définir l'environnement de déploiement (ici, Node.js)
type: nodejs:16  # Version de Node.js à utiliser

# Définir la commande à utiliser pour démarrer le serveur
hooks:
  deploy:
    # Utiliser npm install sous forme de chaîne de caractères
    - "npm install"

web:
  locations:
    "/":
      root: "les-Niçois"  # Répertoire contenant les fichiers statiques
      index: "index.html"  # Fichier index à servir par défaut
      scripts:
        start: "server/server.js"
