# Nom de l'application
name: app

# Type d'application avec version de Node.js
type: nodejs:16

# Taille du disque allouée (en Mo)
disk: 1024

# Commandes exécutées après le déploiement
hooks:
  build: |
    # Accéder directement au répertoire 'server' situé à la racine du projet
    cd server
    npm install

# Commandes exécutées après le déploiement
web:
  commands:
    start: cd server && npm start
  locations:
    "/":
      allow: true
