# Nom de l'application
name: app

# Type d'application avec version de Node.js
type: nodejs:16

# Taille du disque allouée (en Mo)
disk: 1024

# Commandes exécutées après le déploiement
hooks:
  build: |
    cd server
    npm install

# Configuration du service web
web:
  commands:
    start: npm start
  locations:
    "/":
      allow: true
